### ISSUE TITLE
[QUESTION] - Blacklist by section

### ISSUE THREAD

**Issue by Anthony-76** [duggytuxy/malicious_ip_addresses#1]
Hi,

Your job is very wel.

Just a question. Is it possible to have blacklist by section (multi files)?

For example:

ssh-brute-force.txt that contains ip adresses list of brutefoce
C2-cobaltstrike.txt that contains ip addresses list of C2

etc...

Best regards
Anthony

**Comment by duggytuxy** [comment]
Hi Anthony,

I'm going to create a file segmentation based on classifications.

This job is on my roadmap.

Regards,
Laurent

**Comment by Anthony-76** [comment]
Hi,

Nice.

Thank you again for your job

Best regards
Anthony

**Comment by duggytuxy** [comment]
New roadmap is on the way ;-)

**Comment by Anthony-76** [comment]
Hi, 

Any update about this ticket?

thank you again for your great job

**Comment by duggytuxy** [comment]
Hi Anthony,

I'm working with my colleagues for splitting all lists with classifications. I'll advice you when will be ready ;-)

See ya ;-)
