### ISSUE TITLE
Private IP in list

### ISSUE THREAD

**Issue by CTIMarc** [duggytuxy/malicious_ip_addresses#6]
Hello and thanks for your work,

As we can see in today's file (https://github.com/duggytuxy/malicious_ip_addresses/blob/d2d4085f4cc44f417368848206d3ca4ad78d2e47/botnets_zombies_scanner_spam_ips.txt) there is a private IP in the list.
`172.18.0.1`

Can you make adjustment on your side to avoid private IP from RFC in your lists ? 

Cheers

**Comment by duggytuxy** [comment]
Hello,

Indeed. I just removed it ;-).

Thanks ;-)

Cheers

**Comment by duggytuxy** [comment]
172.18.0.1 removed
