### ISSUE TITLE
Telegram API blocked

### ISSUE THREAD

**Issue by chatainsim** [duggytuxy/malicious_ip_addresses#7]
Hello,
Since yesterday, I wasn't able to reach api.telegram.org from home.
I'm using OPNSense with your block list and I finally found that IP of api.telegram.org is blacklisted by your list.
IP: 149.154.167.220

Is it normal ?
Thanks

**Comment by duggytuxy** [comment]
Hello,

I've received several reports of malware delivery from this IP Address.

Normally, you configure these BlockList on incoming "inbound" rules instead of "outbound".

I'm going to remove this from my BL.

Sorry for this inconvenience.

Sincerely,
Duggy

**Comment by duggytuxy** [comment]
Done
